name: Terraform Apply on Merge

on:
  issue_comment:
    types: [created]

jobs:
  terraform-apply:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
    
      - name: Terraform Init
        run: terraform init

      - name: Download Plan
        id: download-plan
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: pr-plan.yml
          pr: ${{ github.event.issue.number }}
          name: ${{ github.event.issue.number }}-tf-plan
          path: .

      - name: Terraform Apply
        run: terraform apply tfplan
